// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAFj26g4XOGtN42a0-_RqZOOVsb5-EODc',
    appId: '1:63865394189:web:c396283fc23d2ee9977144',
    messagingSenderId: '63865394189',
    projectId: 'chatapp-8b868',
    authDomain: 'chatapp-8b868.firebaseapp.com',
    storageBucket: 'chatapp-8b868.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1gXs83rLKhm87v9kzH07O3yZ4GP-Ux58',
    appId: '1:63865394189:android:055602ce4402b871977144',
    messagingSenderId: '63865394189',
    projectId: 'chatapp-8b868',
    storageBucket: 'chatapp-8b868.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9ypqyCZmLZ0Uu5MdYdSn9aRSZD3fUtZ0',
    appId: '1:63865394189:ios:58480d533ce27172977144',
    messagingSenderId: '63865394189',
    projectId: 'chatapp-8b868',
    storageBucket: 'chatapp-8b868.appspot.com',
    iosClientId: '63865394189-0kkgift9q5i0l6e26hocqt7rv3dhkf7v.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9ypqyCZmLZ0Uu5MdYdSn9aRSZD3fUtZ0',
    appId: '1:63865394189:ios:58480d533ce27172977144',
    messagingSenderId: '63865394189',
    projectId: 'chatapp-8b868',
    storageBucket: 'chatapp-8b868.appspot.com',
    iosClientId: '63865394189-0kkgift9q5i0l6e26hocqt7rv3dhkf7v.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
